name: Package Project

on: [ push ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    script:
      - cd core

    steps:
      - uses: actions/checkout@v3
      - name: Python set up
        uses: actions/setup-python@v3
      - name: deps installation
        run: make deps
      - name: make api tests
        run: make test