name: Package Project

on: [ push ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python set up
        uses: actions/setup-python@v3
      - name: go to core folder
        uses: cd core
      - name: deps installation
        run: make deps
      - name: make api tests
        run: make test